name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      name: Node.js CI
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'config.json'
      env:
        token: "00000000000000000000000000000000000000000000000000000000000"
        clientId: "000000000000000000"
        guildId: "000000000000000000"
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
